#include "stdio.h"
#include "set.h"
#include "string.h"
#include "stdint.h"
char *MOVES = {"CAAACCCCCABBABBCBCABBCBACCCAAACCCBBBACCCCBACACACCAABBCCAABCAAACCACCCACBBCACBBCBBCAACBBBBCCBBBCAABCCACCAAACBACACCABBCBCCABBAACBCACBBBBBABCACCABBBACCBABCAAABBBABAAAAACCACACBBBCCAAACAAAAACBCBBBBCCBBACBBBBCCABACABBBBBAABBABCCCCBAAAAAABBAACACBAAABBBCBCCAAAACCCCCBCAACCBAACBBABBBABABCCBCAACBAACACCCCCBAABAABCCABBABBBBABCABBBACAACACCBBCCCACCBBCCABCCBCCBACBCCCCBBBBAABBBCBBCBAABABABCBCCCABCBCCABBBCBBABCCABBCCABABABBCABBBCBBBBBBBCAAABCAABCACABBCABABBCCBAAACAABABABBABBBCABABBBBBCBCBABCCBCAACBCBCACCCABABCAABABBCCACABBAAABABCAAAAABACBCACBACBBCBAABCAACABCCACBBCBACBCBBCBCABBBCCCCAAACCCCBAACBBABAAAABBCAABBCBCBACBCBBACAACBABBCCBACCBABCBACCCCABCACABABBAAABAAACBCCACCCCBCAABBAABACAABBBAACCBAABACBCBBABCCCCBAAACBBCCCCCCCBBBCCBACCCCBBCBBBCBACBBCABBBBBACBCBABCBCCBBCACBAAACBBAABBABCBABCBCCABBBCCBABBCBABCCBABABABAACABBCBABCBACCCBBBBBBAABCBCAACCBABCAACBCABCCCAABCBCACCCBCABBAACAABACCBBCCCABBBBAAACBACABCACBCAACCBABBAAAAAAABCBBBABCCBBCCAAABAABBACABCBBCCCCBBBCBBCACBACBCAACAAABCAABABBAACCBBCACACCAACCCBBAAABCAAABCACABAACACBAABACBCCACBACACCCCCCCAABACAABAAAABBAACBCCACBBACAACBCCBCAAAAABBBCABBCBACBCACCBAABBBBBACABAAACACBBBACCCBACBBACAAACABBABAAACCCBAAABABBCBCCBBBBACBABBBCCBACABBCBABCACAACCABCBCCBAACABCAACBBBCACCCAACABBABBACBCBCCACABBBCBCACAAAABACBAABBBAABCABAABABCCBBCBCABCCBACABCBBCAAABBABCABBAABCCABBBACABABBBACBBBBBBACABACABCBBBCABCBABBBCCABCBAACACBCBCAABBCABBCACCABCABBCACAAABAAABBACCABCABAACCCABAACBBABAAACACACABCBAAABBBCBBBAABCBAABCAACCBCACCCAACBCABABCACAACABBBAABACCCBBBBACAACCCCCCBCACCACCBBACACCCAACBCCCABBBCBCABBBBABACBCBBABAAACAABACBABBCBABAABBAABBAABAACBACBBBBBABBAAACCABBBACAAACABCAABABCBBBCACABCCCBBAABACBBAAACBCAACAAACAAAABCBCBABACCBCACABBACCCCABAABABCCCACAABCBCBABAABBABAACBABACBBBBBAACABCABCBCABACCABCAABCAACCBAABCCABAACBCBBACAAACBBAAABCACCAABBBACBBBABCAACCBCBAAACBCABABBBBABACBAACBBAAABABBAABACAAABCBBAABCCBCBABACAACBCCCACCACABCBCAACCAABCBABCCBAACACBBCABCCBAAACBCCAAAABBCBCBCBBCBACCBCACCBBBBCBBCACCCABACAACBCCBABBACACBABBCCAABCBAACCBCBAABBBBBCBCBABCAABCACCBCCCBCACACACBCCBBBCACAABABAAABBCBBCACABBCBBBBBACCABACCCCAABCACBACCCAABABABABAAACCABACBBAACBCCA\0"}; 

typedef struct tuple{
    int x;
    int y;
} tuple;
tuple DIRECTIONS[4] = {{1,0}, {0,1}, {-1,0}, {0,-1}};
tuple move(tuple current, tuple beacon){
    return (tuple){(current.x + beacon.x)/2, (current.y + beacon.y)/2};
}
void tuple_printTuple(tuple a){
    printf("(%d, %d)\n", a.x, a.y);
}
int linear_find(tuple *arr, int len, tuple t){
    for(int i = 0; i < len; i++){
        if(t.x == arr[i].x && t.y == arr[i].y)
            return 1;
    }
    return 0;
}
// increasing buffer size helped here :)
int main(int argc, char **argv){
    tuple current = {50,0};
    tuple a = {0,0};
    tuple b = {100,0};
    tuple c = {50, 100};
    tuple visited[10000];
    int visited_len = 0;
    visited[visited_len++] = current;
    int nx, ny;
    for(int i = 0; i<strlen(MOVES); i++){
        char dir = MOVES[i];
        if(dir== 'A') current = move(current, a);
        else if (dir == 'B')current = move(current, b);
        else current = move(current, c);
        tuple_printTuple(current);
        if(!linear_find(visited, visited_len, current)){
            visited[visited_len++] = current;
        }
    }
    int f_len = 0;
    tuple f[100000];
    for(int i =0; i < visited_len; i++){
        tuple center = visited[i];
        for(int j =0; j < 4; j++){
            int dx = DIRECTIONS[j].x;
            int dy = DIRECTIONS[j].y;
            tuple pos = {center.x +dx, center.y +dy};
            if(!linear_find(f,f_len,pos) &&
              (!linear_find(visited, visited_len, pos)))
                f[f_len++]=pos;
        }
    }
    printf("%d\n", f_len);
    return 0;
}
